### ISSUE TITLE
Reduce margin around textbook icons

### ISSUE THREAD

**Issue by andymcmillan** [citizenryapp/app#15]
Right now they're all a bit too far away from each other. Can you make it so they're a little tighter together, like in the Figma mockup?

I also don't know the correct terminology here. Does "padding" and "margin" work? What units are used to set values like this in iOS apps? px? em? I have no idea 🙃 but would love to know

![IMG_4131](https://github.com/citizenryapp/app/assets/9889/6e75a428-345d-4f58-a9cc-f2f2e23d4556)
![IMG_4132](https://github.com/citizenryapp/app/assets/9889/71a03c28-3d5f-42e6-9111-bf0ad6e203bc)

**Comment by ajabeckett** [comment]
I'd be happy to use CSS terminology and "px" references! It doesn't map 100% to what's happening in SwiftUI, largely because so much is dependent on device/accessibility variations, but I think those are useful ways to talk about layout/sizing.
