### ISSUE TITLE
Increase time for speech recognition button to timeout

### ISSUE THREAD

**Issue by andymcmillan** [citizenryapp/app#20]
I'm not sure where it's set currently, but I paused a few times last night when answering and it seemed to switch off pretty quickly. Maybe increase the timing a little?

**Comment by ajabeckett** [comment]
I bumped it up a little bit, let's see how this feels. My guess is that the speech button is more of a design problem than a timing problem; it's just not clear enough what the user is expected to do, or what's happening.
