### ISSUE TITLE
Consider consistent naming convention for "election data"

### ISSUE THREAD

**Issue by andymcmillan** [citizenryapp/app#21]
Right now we're saying "sync election data", "local data", prompting users to enter their "mailing address". The app isn't currently explaining what this information is or why we need it especially well.

Understanding that users are likely to hesitant, or at least skeptical, to share their home address, we should figure out what we're calling this and how we're reassuring users about what we're actually using it for.

What do you think?

**Comment by ajabeckett** [comment]
"zip code" only to start, then prompt for specific house district/address if multiple reps.
