### ISSUE TITLE
Changing your language doesn't currently have an option for not setting a secondary language

### ISSUE THREAD

**Issue by andymcmillan** [citizenryapp/app#25]
I think we have a difference of opinion on whether or not we allow users to not set a secondary language, but to me, it's a little odd going into the language settings with an "Off" state, tapping a language, then not being able to return to that off state again. 

Could this be solved by the first option being "Off" or "None"? What do you think?

**Comment by ajabeckett** [comment]
I like the concept of having/not having a "secondary language". Hmm.

**Comment by ajabeckett** [comment]
Still need to decide what to do with the quick settings menu if there's no secondary language, I don't want to take it away...
