### ISSUE TITLE
Speech and microphone access prompt returns when you redo onboarding

### ISSUE THREAD

**Issue by andymcmillan** [citizenryapp/app#3]
Not crucial as I understand restarting onboarding will be hidden, but just in case the fix for this prevents this from happening in the main app I thought it was worth mentioning.

![IMG_4140](https://github.com/citizenryapp/app/assets/9889/7ff61da1-8f2c-4f3f-93a2-cdd2ea928e22)

**Comment by andymcmillan** [comment]
Should mention, this doesn't block progress, if you tap on either option it removes the prompt and moves on to the mock interview.

**Comment by ajabeckett** [comment]
Good catch, but this is on purpose, and only happens in onboarding. I decided to do it this way because I didn't want to risk setting up a different process for repeated onboarding that might inadvertently break regular onboarding.
