### ISSUE TITLE
Addition of "Start Quiz" prompt at the top the textbook

### ISSUE THREAD

**Issue by andymcmillan** [citizenryapp/app#36]
I noticed you added a way to start the quiz above the audio player in the textbook. Is that intention? Do you think you should be able to start the quiz from both the top and the bottom?

**Comment by ajabeckett** [comment]
Maybe? It's nice for the "all 100 questions" quiz, especially since you can't reach that any other way, and the list is long. Maybe "all 100" could be an option on the Practice view, too?
