### ISSUE TITLE
Mock interview Civics test behavior different to actual naturalization interview

### ISSUE THREAD

**Issue by andymcmillan** [citizenryapp/app#37]
Similar to #34, it seems the civics test in the mock interview asks 10 questions regardless of how many you got right. In the actual interview, they stop when you've passed at 60%. 

Again, is this worth keeping consistent with the interview, or not a big deal?

**Comment by ajabeckett** [comment]
It stops when you get 6 right, or finish 10! There are definitely some kinks to iron out with the chat scoring of answers, so you're getting questions marked incorrect that shouldn't be.
