### ISSUE TITLE
Timestamp takes line break with when specific numerals exceed width

### ISSUE THREAD

**Issue by andymcmillan** [citizenryapp/app#4]
The audio player in the textbook during onboarding and the audio player in the textbook in the app are slightly different, the former having a larger text size for the time which forces a line break on wider numerals.

![IMG_4143](https://github.com/citizenryapp/app/assets/9889/c274b663-05b2-47df-8973-73204d386ed6)

**Comment by ajabeckett** [comment]
Fixed onboarding font size to match
