### ISSUE TITLE
App audio doesn't current route through Bluetooth headphones

### ISSUE THREAD

**Issue by andymcmillan** [citizenryapp/app#8]
Not sure how iOS handles routing audio, but I was testing the app with my headphones on last night, and everything was playing through my phone speaker.

**Comment by andymcmillan** [comment]
Not sure if you already looked at this, but I just fired up the mock interview again, and it's working fine. Not sure if maybe a different issue caused this last night?

**Comment by ajabeckett** [comment]
No, it was a bug. There are two different places the AudioSession was being initialized; when you hit the first one, it didn't work. When you hit the second one, it did. I just fixed it, will be in the next testflight build.
